apiVersion: apps/v1
kind: Deployment
metadata:
  name: imdb
  labels:
    app: imdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imdb
  template:
    metadata:
      labels:
        app: imdb
    spec:
      containers:
      - name: imdb
        image: 996203102900.dkr.ecr.us-east-1.amazonaws.com/imdb:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: CAPSTONE_TEST
          valueFrom:
            secretKeyRef:
              name: capstone-secret
              key: CAPSTONE_TEST

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: imdb
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000